#!/bin/sh
# Change UID to the one from user
# NOTE: You cannot change the uid of the running process, so this must happen as root. Use -e USERSPACE=1 instead of --user=www-data at docker-compose

set -e
USERNAME="node"
GROUPNAME=${USERNAME}

# Change uid of the user.
OLDUID=`id -u ${USERNAME}`
if [ `id -u ${OLDUID}` != ${UID} ]; then
    usermod -u ${UID} ${USERNAME}
    find / -xdev -user ${OLDUID} -exec chown ${UID} {} +
fi
OLDGID=`id -g ${GROUPNAME}`
if [ `id -g ${OLDGID}` != ${GID} ]; then
    groupmod -g ${GID} ${GROUPNAME}
    find / -xdev -group ${OLDGID} -exec chgrp ${GID} {} +
fi

# Call parent entrypoint (as other user) when needed
if [ ! -z ${USERSPACE} ]; then
    # Downgrade to ${USERNAME}
    sudo -u ${USERNAME} "$@"
else
    # Run as same user (root)
    exec "$@"
fi
